### ISSUE TITLE
feat: convert to, or create, a template repository

### ISSUE THREAD

**Issue by nokome** [stencila/demo-codespace#3]
There is some interest from users in having their own Codespaces, with the R and Python packages they need in it, along with the Stencila VSCode extension.

We could make this a template repository, or create a new one that is a template repo, with instructions on how to customize in the README.md the Codespace (e.g. add packages in the Dockerfile, or perhaps a `pyproject.toml` etc?).

If possible, I think it would be better not to create a new repo and instead and instead add those instructions here.

**Comment by jduckles** [comment]
If you have docker on your system, `.devcontainers` can be run locally with the "Dev Containers" extenstion...it is yet another context to manage, but isn't that the work of modern compute environments 🫠 . So just saying we could give people the easy (but costs option) and some docs for the local optiion (if they know / have Docker already).

**Comment by nokome** [comment]
> So just saying we could give people the easy (but costs option) and some docs for the local optiion (if they know / have Docker already).

Could you put those docs for the local option in the README under the "Launching the demo" and maybe rename that heading so we have something like "Launching in the cloud" + "Launching locally".
